import Head from "next/head";
import products from "../products.json";
import styles from "../styles/Home.module.css";
import { fromImageToUrl } from "../utils/urls";
import Link from "next/link";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next Appa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
test
      {products.map((product) => (
        <div key={product.name} className={styles.product}>
          <Link href="/">
            <div className={styles.product__Row}>
              <div className={styles.product__ColImg}>
                <img
                  className={styles.product__Im}
                  src={fromImageToUrl(product.image)}
                  alt=""
                />
              </div>
              <div className={styles.product__Col}>
                {product.name} {product.price}
              </div>
            </div>
          </Link>
        </div>
      ))}
    </div>
  );
};

export default Home;
